import type { ThemeSettings } from "@shared/schema";

// Pre-built themes for the application
export const defaultThemes: { id: string; name: string; description: string; isPremium: boolean; settings: ThemeSettings }[] = [
  {
    id: "minimal",
    name: "Minimal",
    description: "Clean and simple with high contrast",
    isPremium: false,
    settings: {
      background: "#ffffff",
      backgroundType: "solid",
      textColor: "#1a1a1a",
      buttonStyle: "outlined",
      buttonShape: "rounded-full",
      buttonBackground: "#ffffff",
      buttonTextColor: "#1a1a1a",
      buttonBorderColor: "#1a1a1a",
      fontFamily: "Inter",
      accentColor: "#3b82f6",
    },
  },
  {
    id: "dark-minimal",
    name: "Dark Minimal",
    description: "Sleek dark mode design",
    isPremium: false,
    settings: {
      background: "#0a0a0a",
      backgroundType: "solid",
      textColor: "#fafafa",
      buttonStyle: "outlined",
      buttonShape: "rounded-full",
      buttonBackground: "transparent",
      buttonTextColor: "#fafafa",
      buttonBorderColor: "#fafafa",
      fontFamily: "Inter",
      accentColor: "#8b5cf6",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    description: "Warm gradient with golden hues",
    isPremium: false,
    settings: {
      background: "linear-gradient(135deg, #ff6b6b 0%, #feca57 100%)",
      backgroundType: "gradient",
      gradientFrom: "#ff6b6b",
      gradientTo: "#feca57",
      gradientDirection: "135deg",
      textColor: "#ffffff",
      buttonStyle: "filled",
      buttonShape: "rounded-full",
      buttonBackground: "rgba(255,255,255,0.25)",
      buttonTextColor: "#ffffff",
      fontFamily: "Poppins",
      accentColor: "#ff6b6b",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Cool blue tones with depth",
    isPremium: false,
    settings: {
      background: "linear-gradient(180deg, #0077b6 0%, #00b4d8 50%, #90e0ef 100%)",
      backgroundType: "gradient",
      gradientFrom: "#0077b6",
      gradientTo: "#90e0ef",
      gradientDirection: "180deg",
      textColor: "#ffffff",
      buttonStyle: "filled",
      buttonShape: "rounded-xl",
      buttonBackground: "rgba(255,255,255,0.2)",
      buttonTextColor: "#ffffff",
      fontFamily: "Inter",
      accentColor: "#00b4d8",
    },
  },
  {
    id: "forest",
    name: "Forest",
    description: "Natural earthy greens",
    isPremium: false,
    settings: {
      background: "linear-gradient(180deg, #2d5016 0%, #4a7c23 100%)",
      backgroundType: "gradient",
      gradientFrom: "#2d5016",
      gradientTo: "#4a7c23",
      gradientDirection: "180deg",
      textColor: "#ffffff",
      buttonStyle: "filled",
      buttonShape: "rounded-lg",
      buttonBackground: "rgba(255,255,255,0.15)",
      buttonTextColor: "#ffffff",
      fontFamily: "Open Sans",
      accentColor: "#84cc16",
    },
  },
  {
    id: "neon",
    name: "Neon Nights",
    description: "Vibrant cyberpunk aesthetic",
    isPremium: true,
    settings: {
      background: "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)",
      backgroundType: "gradient",
      gradientFrom: "#0f0c29",
      gradientTo: "#24243e",
      gradientDirection: "135deg",
      textColor: "#ffffff",
      buttonStyle: "outlined",
      buttonShape: "rounded-lg",
      buttonBackground: "transparent",
      buttonTextColor: "#f472b6",
      buttonBorderColor: "#f472b6",
      fontFamily: "Space Grotesk",
      accentColor: "#f472b6",
      animations: {
        buttonHover: "glow",
        buttonTransition: "smooth",
        entranceAnimation: "slide",
        backgroundAnimation: "none",
      },
    },
  },
  {
    id: "aurora",
    name: "Aurora",
    description: "Mesmerizing northern lights",
    isPremium: true,
    settings: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 25%, #6B8DD6 50%, #8E37D7 75%, #667eea 100%)",
      backgroundType: "mesh",
      gradientFrom: "#667eea",
      gradientTo: "#764ba2",
      gradientDirection: "135deg",
      textColor: "#ffffff",
      buttonStyle: "soft",
      buttonShape: "rounded-full",
      buttonBackground: "rgba(255,255,255,0.2)",
      buttonTextColor: "#ffffff",
      fontFamily: "Plus Jakarta Sans",
      accentColor: "#a78bfa",
      animations: {
        buttonHover: "shimmer",
        buttonTransition: "bouncy",
        entranceAnimation: "zoom",
        backgroundAnimation: "gradient-shift",
      },
    },
  },
  {
    id: "glassmorphism",
    name: "Glass",
    description: "Modern frosted glass effect",
    isPremium: true,
    settings: {
      background: "linear-gradient(135deg, #1e3a5f 0%, #2d5a7b 50%, #1e3a5f 100%)",
      backgroundType: "gradient",
      gradientFrom: "#1e3a5f",
      gradientTo: "#2d5a7b",
      gradientDirection: "135deg",
      textColor: "#ffffff",
      buttonStyle: "soft",
      buttonShape: "rounded-xl",
      buttonBackground: "rgba(255,255,255,0.1)",
      buttonTextColor: "#ffffff",
      fontFamily: "Inter",
      accentColor: "#60a5fa",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "Deep purple elegance",
    isPremium: true,
    settings: {
      background: "linear-gradient(180deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
      backgroundType: "gradient",
      gradientFrom: "#1a1a2e",
      gradientTo: "#0f3460",
      gradientDirection: "180deg",
      textColor: "#e0e0e0",
      buttonStyle: "filled",
      buttonShape: "rounded-full",
      buttonBackground: "rgba(233, 69, 96, 0.8)",
      buttonTextColor: "#ffffff",
      fontFamily: "Outfit",
      accentColor: "#e94560",
    },
  },
  {
    id: "candy",
    name: "Candy",
    description: "Sweet pastel vibes",
    isPremium: true,
    settings: {
      background: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 50%, #ff9a9e 100%)",
      backgroundType: "gradient",
      gradientFrom: "#ffecd2",
      gradientTo: "#ff9a9e",
      gradientDirection: "135deg",
      textColor: "#4a3728",
      buttonStyle: "filled",
      buttonShape: "rounded-full",
      buttonBackground: "rgba(255,255,255,0.7)",
      buttonTextColor: "#4a3728",
      fontFamily: "Poppins",
      accentColor: "#f472b6",
    },
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    description: "Warm orange and yellow sunset glow",
    isPremium: false,
    settings: {
      background: "linear-gradient(135deg, #f59e0b 0%, #fb923c 50%, #fbbf24 100%)",
      backgroundType: "gradient",
      gradientFrom: "#f59e0b",
      gradientTo: "#fbbf24",
      gradientDirection: "135deg",
      textColor: "#ffffff",
      buttonStyle: "filled",
      buttonShape: "rounded-full",
      buttonBackground: "rgba(255,255,255,0.25)",
      buttonTextColor: "#ffffff",
      fontFamily: "Poppins",
      accentColor: "#fbbf24",
    },
  },
  {
    id: "lavender",
    name: "Lavender Dreams",
    description: "Soft purple and pink gradient",
    isPremium: false,
    settings: {
      background: "linear-gradient(180deg, #ddd6f3 0%, #faaca8 100%)",
      backgroundType: "gradient",
      gradientFrom: "#ddd6f3",
      gradientTo: "#faaca8",
      gradientDirection: "180deg",
      textColor: "#4a4a4a",
      buttonStyle: "soft",
      buttonShape: "rounded-xl",
      buttonBackground: "rgba(255,255,255,0.6)",
      buttonTextColor: "#6b4c9a",
      fontFamily: "Inter",
      accentColor: "#c084fc",
    },
  },
  {
    id: "monochrome",
    name: "Monochrome",
    description: "Classic black and white contrast",
    isPremium: false,
    settings: {
      background: "#000000",
      backgroundType: "solid",
      textColor: "#ffffff",
      buttonStyle: "outlined",
      buttonShape: "rounded-none",
      buttonBackground: "transparent",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#ffffff",
      fontFamily: "Space Grotesk",
      accentColor: "#ffffff",
    },
  },
  {
    id: "mint",
    name: "Mint Fresh",
    description: "Cool mint and turquoise blend",
    isPremium: false,
    settings: {
      background: "linear-gradient(135deg, #6ee7b7 0%, #14b8a6 50%, #06b6d4 100%)",
      backgroundType: "gradient",
      gradientFrom: "#6ee7b7",
      gradientTo: "#06b6d4",
      gradientDirection: "135deg",
      textColor: "#ffffff",
      buttonStyle: "filled",
      buttonShape: "rounded-full",
      buttonBackground: "rgba(255,255,255,0.3)",
      buttonTextColor: "#ffffff",
      fontFamily: "Inter",
      accentColor: "#14b8a6",
    },
  },
  {
    id: "cherry-blossom",
    name: "Cherry Blossom",
    description: "Delicate pink spring vibes",
    isPremium: false,
    settings: {
      background: "linear-gradient(180deg, #fce7f3 0%, #fbcfe8 50%, #f9a8d4 100%)",
      backgroundType: "gradient",
      gradientFrom: "#fce7f3",
      gradientTo: "#f9a8d4",
      gradientDirection: "180deg",
      textColor: "#831843",
      buttonStyle: "soft",
      buttonShape: "rounded-full",
      buttonBackground: "rgba(255,255,255,0.7)",
      buttonTextColor: "#9f1239",
      fontFamily: "Poppins",
      accentColor: "#ec4899",
    },
  },
  {
    id: "volcano",
    name: "Volcano",
    description: "Fiery red and orange explosion",
    isPremium: true,
    settings: {
      background: "linear-gradient(135deg, #dc2626 0%, #ea580c 50%, #f59e0b 100%)",
      backgroundType: "gradient",
      gradientFrom: "#dc2626",
      gradientTo: "#f59e0b",
      gradientDirection: "135deg",
      textColor: "#ffffff",
      buttonStyle: "filled",
      buttonShape: "rounded-lg",
      buttonBackground: "rgba(0,0,0,0.3)",
      buttonTextColor: "#ffffff",
      fontFamily: "Space Grotesk",
      accentColor: "#fb923c",
      animations: {
        buttonHover: "lift",
        buttonTransition: "bouncy",
        entranceAnimation: "zoom",
        backgroundAnimation: "gradient-shift",
      },
    },
  },
  {
    id: "cosmic",
    name: "Cosmic",
    description: "Deep space with starry gradients",
    isPremium: true,
    settings: {
      background: "linear-gradient(135deg, #1e1b4b 0%, #312e81 25%, #4c1d95 50%, #6b21a8 75%, #7c2d12 100%)",
      backgroundType: "gradient",
      gradientFrom: "#1e1b4b",
      gradientTo: "#7c2d12",
      gradientDirection: "135deg",
      textColor: "#fef3c7",
      buttonStyle: "soft",
      buttonShape: "rounded-full",
      buttonBackground: "rgba(255,255,255,0.15)",
      buttonTextColor: "#fde047",
      fontFamily: "Space Grotesk",
      accentColor: "#fbbf24",
      animations: {
        buttonHover: "glow",
        buttonTransition: "smooth",
        entranceAnimation: "fade",
        backgroundAnimation: "particles",
      },
    },
  },
  {
    id: "emerald",
    name: "Emerald",
    description: "Rich emerald green luxury",
    isPremium: true,
    settings: {
      background: "linear-gradient(180deg, #064e3b 0%, #047857 50%, #10b981 100%)",
      backgroundType: "gradient",
      gradientFrom: "#064e3b",
      gradientTo: "#10b981",
      gradientDirection: "180deg",
      textColor: "#ffffff",
      buttonStyle: "outlined",
      buttonShape: "rounded-xl",
      buttonBackground: "transparent",
      buttonTextColor: "#ffffff",
      buttonBorderColor: "#d1fae5",
      fontFamily: "Outfit",
      accentColor: "#34d399",
    },
  },
  {
    id: "peach",
    name: "Peach Sorbet",
    description: "Soft peachy orange gradient",
    isPremium: true,
    settings: {
      background: "linear-gradient(135deg, #fed7aa 0%, #fdba74 50%, #fb923c 100%)",
      backgroundType: "gradient",
      gradientFrom: "#fed7aa",
      gradientTo: "#fb923c",
      gradientDirection: "135deg",
      textColor: "#7c2d12",
      buttonStyle: "filled",
      buttonShape: "rounded-full",
      buttonBackground: "rgba(255,255,255,0.8)",
      buttonTextColor: "#9a3412",
      fontFamily: "Poppins",
      accentColor: "#f97316",
    },
  },
  {
    id: "royal",
    name: "Royal Blue",
    description: "Majestic deep blue elegance",
    isPremium: true,
    settings: {
      background: "linear-gradient(180deg, #1e3a8a 0%, #1e40af 50%, #3b82f6 100%)",
      backgroundType: "gradient",
      gradientFrom: "#1e3a8a",
      gradientTo: "#3b82f6",
      gradientDirection: "180deg",
      textColor: "#ffffff",
      buttonStyle: "soft",
      buttonShape: "rounded-lg",
      buttonBackground: "rgba(255,255,255,0.2)",
      buttonTextColor: "#ffffff",
      fontFamily: "Inter",
      accentColor: "#60a5fa",
    },
  },
  {
    id: "matrix",
    name: "Matrix",
    description: "Digital green code aesthetic",
    isPremium: true,
    settings: {
      background: "#000000",
      backgroundType: "solid",
      textColor: "#00ff00",
      buttonStyle: "outlined",
      buttonShape: "rounded-none",
      buttonBackground: "transparent",
      buttonTextColor: "#00ff00",
      buttonBorderColor: "#00ff00",
      fontFamily: "Space Grotesk",
      accentColor: "#00ff00",
    },
  },
  {
    id: "caramel",
    name: "Caramel",
    description: "Warm brown and beige tones",
    isPremium: true,
    settings: {
      background: "linear-gradient(135deg, #78350f 0%, #92400e 50%, #b45309 100%)",
      backgroundType: "gradient",
      gradientFrom: "#78350f",
      gradientTo: "#b45309",
      gradientDirection: "135deg",
      textColor: "#fef3c7",
      buttonStyle: "filled",
      buttonShape: "rounded-xl",
      buttonBackground: "rgba(254, 243, 199, 0.2)",
      buttonTextColor: "#fef3c7",
      fontFamily: "Outfit",
      accentColor: "#fbbf24",
    },
  },
  {
    id: "arctic",
    name: "Arctic",
    description: "Icy blue and white winter theme",
    isPremium: true,
    settings: {
      background: "linear-gradient(180deg, #dbeafe 0%, #bfdbfe 50%, #93c5fd 100%)",
      backgroundType: "gradient",
      gradientFrom: "#dbeafe",
      gradientTo: "#93c5fd",
      gradientDirection: "180deg",
      textColor: "#1e3a8a",
      buttonStyle: "soft",
      buttonShape: "rounded-full",
      buttonBackground: "rgba(255,255,255,0.7)",
      buttonTextColor: "#1e40af",
      fontFamily: "Inter",
      accentColor: "#3b82f6",
      animations: {
        buttonHover: "lift",
        buttonTransition: "smooth",
        entranceAnimation: "fade",
        backgroundAnimation: "none",
      },
    },
  },
  // New Free Themes
  {
    id: "coral",
    name: "Coral Reef",
    description: "Vibrant coral and turquoise",
    isPremium: false,
    settings: {
      background: "linear-gradient(135deg, #ff6b9d 0%, #ffa07a 50%, #20b2aa 100%)",
      backgroundType: "gradient",
      gradientFrom: "#ff6b9d",
      gradientTo: "#20b2aa",
      gradientDirection: "135deg",
      textColor: "#ffffff",
      buttonStyle: "filled",
      buttonShape: "rounded-xl",
      buttonBackground: "rgba(255,255,255,0.25)",
      buttonTextColor: "#ffffff",
      fontFamily: "Poppins",
      accentColor: "#ff6b9d",
      requiredTier: "free",
    },
  },
  {
    id: "slate",
    name: "Slate Gray",
    description: "Professional minimalist gray",
    isPremium: false,
    settings: {
      background: "#475569",
      backgroundType: "solid",
      textColor: "#f1f5f9",
      buttonStyle: "outlined",
      buttonShape: "rounded-lg",
      buttonBackground: "transparent",
      buttonTextColor: "#f1f5f9",
      buttonBorderColor: "#cbd5e1",
      fontFamily: "Inter",
      accentColor: "#94a3b8",
      requiredTier: "free",
    },
  },
  {
    id: "cotton-candy",
    name: "Cotton Candy",
    description: "Sweet blue and pink clouds",
    isPremium: false,
    settings: {
      background: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)",
      backgroundType: "gradient",
      gradientFrom: "#a8edea",
      gradientTo: "#fed6e3",
      gradientDirection: "135deg",
      textColor: "#374151",
      buttonStyle: "soft",
      buttonShape: "rounded-full",
      buttonBackground: "rgba(255,255,255,0.6)",
      buttonTextColor: "#6b21a8",
      fontFamily: "Poppins",
      accentColor: "#ec4899",
      requiredTier: "free",
    },
  },
  {
    id: "earth",
    name: "Earth Tones",
    description: "Natural brown and green palette",
    isPremium: false,
    settings: {
      background: "linear-gradient(180deg, #8b7355 0%, #6b8e23 100%)",
      backgroundType: "gradient",
      gradientFrom: "#8b7355",
      gradientTo: "#6b8e23",
      gradientDirection: "180deg",
      textColor: "#fef3c7",
      buttonStyle: "filled",
      buttonShape: "rounded-lg",
      buttonBackground: "rgba(254, 243, 199, 0.2)",
      buttonTextColor: "#fef3c7",
      fontFamily: "Open Sans",
      accentColor: "#a3e635",
      requiredTier: "free",
    },
  },
  // Starter Pack Themes
  {
    id: "amethyst",
    name: "Amethyst",
    description: "Rich purple with subtle animations",
    isPremium: false,
    settings: {
      background: "linear-gradient(135deg, #6b46c1 0%, #9333ea 50%, #c026d3 100%)",
      backgroundType: "gradient",
      gradientFrom: "#6b46c1",
      gradientTo: "#c026d3",
      gradientDirection: "135deg",
      textColor: "#faf5ff",
      buttonStyle: "soft",
      buttonShape: "rounded-xl",
      buttonBackground: "rgba(255,255,255,0.2)",
      buttonTextColor: "#ffffff",
      fontFamily: "Inter",
      accentColor: "#d946ef",
      animations: {
        buttonHover: "scale",
        buttonTransition: "smooth",
        entranceAnimation: "fade",
        backgroundAnimation: "none",
      },
      requiredTier: "starter",
    },
  },
  {
    id: "cyber-blue",
    name: "Cyber Blue",
    description: "Futuristic blue with glow effects",
    isPremium: false,
    settings: {
      background: "linear-gradient(135deg, #0c4a6e 0%, #0369a1 50%, #0ea5e9 100%)",
      backgroundType: "gradient",
      gradientFrom: "#0c4a6e",
      gradientTo: "#0ea5e9",
      gradientDirection: "135deg",
      textColor: "#e0f2fe",
      buttonStyle: "outlined",
      buttonShape: "rounded-lg",
      buttonBackground: "transparent",
      buttonTextColor: "#7dd3fc",
      buttonBorderColor: "#38bdf8",
      fontFamily: "Space Grotesk",
      accentColor: "#0ea5e9",
      animations: {
        buttonHover: "glow",
        buttonTransition: "smooth",
        entranceAnimation: "slide",
        backgroundAnimation: "none",
      },
      requiredTier: "starter",
    },
  },
  {
    id: "rose-gold",
    name: "Rose Gold",
    description: "Elegant rose gold shimmer",
    isPremium: false,
    settings: {
      background: "linear-gradient(135deg, #be185d 0%, #db2777 25%, #f472b6 50%, #fbbf24 100%)",
      backgroundType: "gradient",
      gradientFrom: "#be185d",
      gradientTo: "#fbbf24",
      gradientDirection: "135deg",
      textColor: "#ffffff",
      buttonStyle: "filled",
      buttonShape: "rounded-full",
      buttonBackground: "rgba(255,255,255,0.25)",
      buttonTextColor: "#ffffff",
      fontFamily: "Poppins",
      accentColor: "#f9a8d4",
      animations: {
        buttonHover: "shimmer",
        buttonTransition: "smooth",
        entranceAnimation: "zoom",
        backgroundAnimation: "none",
      },
      requiredTier: "starter",
    },
  },
  {
    id: "forest-night",
    name: "Forest Night",
    description: "Deep forest with moonlight",
    isPremium: false,
    settings: {
      background: "linear-gradient(180deg, #052e16 0%, #14532d 50%, #166534 100%)",
      backgroundType: "gradient",
      gradientFrom: "#052e16",
      gradientTo: "#166534",
      gradientDirection: "180deg",
      textColor: "#d1fae5",
      buttonStyle: "soft",
      buttonShape: "rounded-xl",
      buttonBackground: "rgba(209, 250, 229, 0.15)",
      buttonTextColor: "#d1fae5",
      fontFamily: "Inter",
      accentColor: "#4ade80",
      animations: {
        buttonHover: "lift",
        buttonTransition: "smooth",
        entranceAnimation: "fade",
        backgroundAnimation: "none",
      },
      requiredTier: "starter",
    },
  },
];

export function getThemeBackground(settings: ThemeSettings): string {
  if (settings.backgroundType === "solid") {
    return settings.background;
  }
  return settings.background;
}

export function getButtonStyles(settings: ThemeSettings): React.CSSProperties {
  const baseStyles: React.CSSProperties = {
    fontFamily: settings.fontFamily,
    color: settings.buttonTextColor,
  };

  switch (settings.buttonStyle) {
    case "filled":
      return {
        ...baseStyles,
        backgroundColor: settings.buttonBackground,
        border: "none",
      };
    case "outlined":
      return {
        ...baseStyles,
        backgroundColor: "transparent",
        border: `2px solid ${settings.buttonBorderColor || settings.buttonTextColor}`,
      };
    case "soft":
      return {
        ...baseStyles,
        backgroundColor: settings.buttonBackground,
        backdropFilter: "blur(10px)",
        border: "1px solid rgba(255,255,255,0.1)",
      };
    default:
      return baseStyles;
  }
}
